# Generated by Django 3.0.4 on 2020-04-01 05:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_address_country_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='')),
                ('careate', models.DateTimeField(verbose_name=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SellerBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(default=django.utils.timezone.now)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Bank')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Seller')),
            ],
        ),
    ]
