# Generated by Django 3.0.4 on 2020-04-01 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_bank_sellerbank'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerbank',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
