# Generated by Django 3.0.4 on 2020-04-02 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_city_tumbon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='city',
        ),
        migrations.RemoveField(
            model_name='address',
            name='street',
        ),
        migrations.RemoveField(
            model_name='address',
            name='tumbon',
        ),
        migrations.AlterField(
            model_name='address',
            name='number',
            field=models.TextField(null=True),
        ),
    ]
