# Generated by Django 3.0.4 on 2020-04-27 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_auto_20200403_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerbank',
            name='namebank',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
