# Generated by Django 3.0.4 on 2020-04-27 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_sellerbank_namebank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tumbon',
            name='city',
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='tumbon',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Tumbon',
        ),
    ]
