# Generated by Django 3.0.4 on 2020-04-16 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_auto_20200403_0223'),
        ('cart', '0004_auto_20200416_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paycart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='')),
                ('payed', models.BooleanField(default=True)),
                ('cartitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.CartItem')),
                ('sellerbank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.SellerBank')),
            ],
        ),
    ]
