# Generated by Django 3.0.4 on 2020-04-18 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_delete_payment'),
        ('cart', '0005_paycart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paycart',
            name='cartitem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.OrderItem'),
        ),
    ]
