# Generated by Django 3.0.4 on 2020-04-26 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_auto_20200403_0223'),
        ('cart', '0006_auto_20200418_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paycart',
            name='sellerbank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.SellerBank'),
        ),
    ]
