# Generated by Django 3.0.4 on 2020-04-27 01:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_auto_20200426_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='paycart',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
