# Generated by Django 3.0.4 on 2020-04-27 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_auto_20200427_0818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paycart',
            name='sellerbank',
        ),
    ]
