# Generated by Django 3.0.4 on 2020-04-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_remove_paycart_sellerbank'),
    ]

    operations = [
        migrations.AddField(
            model_name='paycart',
            name='simage_url',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
