# Generated by Django 3.0.4 on 2020-04-01 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_sellerbank_number'),
        ('order', '0002_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.SellerBank'),
        ),
    ]
