# Generated by Django 3.0.4 on 2020-04-07 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_remove_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='nameorder',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
