# Generated by Django 3.0.4 on 2020-04-07 08:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0009_auto_20200407_1346'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Order1',
        ),
    ]
