# Generated by Django 3.0.4 on 2020-04-11 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_delete_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
    ]
