# Generated by Django 3.0.4 on 2020-04-11 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_remove_orderitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='create',
        ),
    ]
