# Generated by Django 3.0.4 on 2020-04-16 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_auto_20200403_0223'),
        ('order', '0018_order_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='')),
                ('status', models.BooleanField(default=False)),
                ('orderitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.OrderItem')),
                ('sellerbank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.SellerBank')),
            ],
        ),
    ]
