# Generated by Django 3.0.4 on 2020-04-27 01:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_delete_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
