# Generated by Django 3.0.4 on 2020-04-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0023_remove_orderitem_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ship',
            field=models.BooleanField(default=False),
        ),
    ]
