# Generated by Django 3.0.4 on 2020-04-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_order_ship'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='ship',
            field=models.BooleanField(default=False),
        ),
    ]
