# Generated by Django 3.0.4 on 2020-04-15 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productsaled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsaled',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='productsaled',
            name='total',
        ),
    ]
